name: ZEDIO CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '1.8'

    - name: Download Dependencies
      run: ./gradlew build --no-daemon

    - name: Run Unit Tests
      run: ./gradlew test --no-daemon

    - name: Build Debug APK
      run: ./gradlew assembleDebug --no-daemon

    - name: Build Release APK
      run: ./gradlew assembleRelease --no-daemon

    - name: Upload Release APK as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: release-apk
        path: app/build/outputs/apk/release/app-release.apk

    - name: Upload Debug APK as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
